apiVersion: v1
kind: Service
metadata:
  name: amberflo-provider-metrics
  labels:
    app.kubernetes.io/name: amberflo-provider
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    control-plane: amberflo-provider
    app.kubernetes.io/name: amberflo-provider
