---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amberflo-provider
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccounts/finalizers
  verbs:
  - update
