apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: amberflo-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amberflo-provider
subjects:
  - kind: ServiceAccount
    name: amberflo-provider
    namespace: amberflo-provider-system
